name: General Feedback
description: Give some informal feedback.
labels: 
 - feedback
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give this feedback!
